version: '3.8'
services:
  tokenization-app:
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    container_name: tokenization-app
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms256m -Xmx512m
